const Icons = [
  {"type":"directory","name":"static/GCP Icons/Products & Services","contents":[
    {"type":"directory","name":"API Platform &amp; Ecosystems","contents":[
      {"type":"file","name":"API Analytics.png"},
      {"type":"file","name":"API Analytics.svg"},
      {"type":"file","name":"API Monetization.png"},
      {"type":"file","name":"API Monetization.svg"},
      {"type":"file","name":"Apigee API Platform.png"},
      {"type":"file","name":"Apigee API Platform.svg"},
      {"type":"file","name":"Apigee Sense.png"},
      {"type":"file","name":"Apigee Sense.svg"},
      {"type":"file","name":"Cloud Endpoints.png"},
      {"type":"file","name":"Cloud Endpoints.svg"},
      {"type":"file","name":"Developer Portal.png"},
      {"type":"file","name":"Developer Portal.svg"}
    ]},
    {"type":"directory","name":"Big Data","contents":[
      {"type":"file","name":"BigQuery.png"},
      {"type":"file","name":"BigQuery.svg"},
      {"type":"file","name":"Cloud Composer.png"},
      {"type":"file","name":"Cloud Composer.svg"},
      {"type":"file","name":"Cloud Dataflow.png"},
      {"type":"file","name":"Cloud Dataflow.svg"},
      {"type":"file","name":"Cloud Datalab.png"},
      {"type":"file","name":"Cloud Datalab.svg"},
      {"type":"file","name":"Cloud Dataprep.png"},
      {"type":"file","name":"Cloud Dataprep.svg"},
      {"type":"file","name":"Cloud Dataproc.png"},
      {"type":"file","name":"Cloud Dataproc.svg"},
      {"type":"file","name":"Cloud PubSub.png"},
      {"type":"file","name":"Cloud PubSub.svg"},
      {"type":"file","name":"Data Studio.png"},
      {"type":"file","name":"Data Studio.svg"},
      {"type":"file","name":"Genomics.png"},
      {"type":"file","name":"Genomics.svg"}
    ]},
    {"type":"directory","name":"Cloud AI","contents":[
      {"type":"file","name":"Advanced Solutions Lab.png"},
      {"type":"file","name":"Advanced Solutions Lab.svg"},
      {"type":"file","name":"Cloud AutoML.png"},
      {"type":"file","name":"Cloud AutoML.svg"},
      {"type":"file","name":"Cloud Jobs API.png"},
      {"type":"file","name":"Cloud Jobs API.svg"},
      {"type":"file","name":"Cloud Machine Learning.png"},
      {"type":"file","name":"Cloud Machine Learning.svg"},
      {"type":"file","name":"Cloud Natural Language API.png"},
      {"type":"file","name":"Cloud Natural Language API.svg"},
      {"type":"file","name":"Cloud Speech API.png"},
      {"type":"file","name":"Cloud Speech API.svg"},
      {"type":"file","name":"Cloud TPU.png"},
      {"type":"file","name":"Cloud TPU.svg"},
      {"type":"file","name":"Cloud Text-to-Speech.png"},
      {"type":"file","name":"Cloud Text-to-Speech.svg"},
      {"type":"file","name":"Cloud Translation API.png"},
      {"type":"file","name":"Cloud Translation API.svg"},
      {"type":"file","name":"Cloud Video Intelligence API.png"},
      {"type":"file","name":"Cloud Video Intelligence API.svg"},
      {"type":"file","name":"Cloud Vision API.png"},
      {"type":"file","name":"Cloud Vision API.svg"},
      {"type":"file","name":"Dialogflow Enterprise Edition.png"},
      {"type":"file","name":"Dialogflow Enterprise Edition.svg"}
    ]},
    {"type":"directory","name":"Compute","contents":[
      {"type":"file","name":"App Engine.png"},
      {"type":"file","name":"App Engine.svg"},
      {"type":"file","name":"Cloud Functions.png"},
      {"type":"file","name":"Cloud Functions.svg"},
      {"type":"file","name":"Compute Engine.png"},
      {"type":"file","name":"Compute Engine.svg"},
      {"type":"file","name":"Container Engine.png"},
      {"type":"file","name":"Container Engine.svg"},
      {"type":"file","name":"Container-Optimized OS.png"},
      {"type":"file","name":"Container-Optimized OS.svg"},
      {"type":"file","name":"GPU.png"},
      {"type":"file","name":"GPU.svg"}
    ]},
    {"type":"directory","name":"Data Transfer","contents":[
      {"type":"file","name":"Transfer Appliance.png"},
      {"type":"file","name":"Transfer Appliance.svg"}
    ]},
    {"type":"directory","name":"Developer Tools","contents":[
      {"type":"file","name":"Cloud Deployment Manager.png"},
      {"type":"file","name":"Cloud Deployment Manager.svg"},
      {"type":"file","name":"Cloud SDK.png"},
      {"type":"file","name":"Cloud SDK.svg"},
      {"type":"file","name":"Cloud Source Repositories.png"},
      {"type":"file","name":"Cloud Source Repositories.svg"},
      {"type":"file","name":"Cloud Test Lab.png"},
      {"type":"file","name":"Cloud Test Lab.svg"},
      {"type":"file","name":"Cloud Tools for Android Studio.png"},
      {"type":"file","name":"Cloud Tools for Android Studio.svg"},
      {"type":"file","name":"Cloud Tools for IntelliJ.png"},
      {"type":"file","name":"Cloud Tools for IntelliJ.svg"},
      {"type":"file","name":"Cloud Tools for PowerShell.png"},
      {"type":"file","name":"Cloud Tools for PowerShell.svg"},
      {"type":"file","name":"Cloud Tools for Visual Studio.png"},
      {"type":"file","name":"Cloud Tools for Visual Studio.svg"},
      {"type":"file","name":"Container Builder.png"},
      {"type":"file","name":"Container Builder.svg"},
      {"type":"file","name":"Container Registry.png"},
      {"type":"file","name":"Container Registry.svg"},
      {"type":"file","name":"Google Plugin for Eclipse.png"},
      {"type":"file","name":"Google Plugin for Eclipse.svg"}
    ]},
    {"type":"directory","name":"Extras","contents":[
      {"type":"file","name":"Blue Hexagon.png"},
      {"type":"file","name":"Blue Hexagon.svg"},
      {"type":"directory","name":"Expanded Product Card Icons","contents":[
        {"type":"file","name":"App-Engine.png"},
        {"type":"file","name":"App-Engine.svg"},
        {"type":"file","name":"Cloud-Dataflow.png"},
        {"type":"file","name":"Cloud-Dataflow.svg"},
        {"type":"file","name":"Cloud-Dataproc.png"},
        {"type":"file","name":"Cloud-Dataproc.svg"},
        {"type":"file","name":"Compute-Engine.png"},
        {"type":"file","name":"Compute-Engine.svg"},
        {"type":"file","name":"Container-Engine.png"},
        {"type":"file","name":"Container-Engine.svg"},
        {"type":"file","name":"modifiers_autoscaling.png"},
        {"type":"file","name":"modifiers_autoscaling.svg"},
        {"type":"file","name":"modifiers_custom-virtual-machine.png"},
        {"type":"file","name":"modifiers_custom-virtual-machine.svg"},
        {"type":"file","name":"modifiers_high-CPU-machine.png"},
        {"type":"file","name":"modifiers_high-CPU-machine.svg"},
        {"type":"file","name":"modifiers_high-memory-machine.png"},
        {"type":"file","name":"modifiers_high-memory-machine.svg"},
        {"type":"file","name":"modifiers_preemptable-vm.png"},
        {"type":"file","name":"modifiers_preemptable-vm.svg"},
        {"type":"file","name":"modifiers_shared-core-machine-F1.png"},
        {"type":"file","name":"modifiers_shared-core-machine-F1.svg"},
        {"type":"file","name":"modifiers_shared-core-machine-G1.png"},
        {"type":"file","name":"modifiers_shared-core-machine-G1.svg"},
        {"type":"file","name":"modifiers_standard-machine.png"},
        {"type":"file","name":"modifiers_standard-machine.svg"},
        {"type":"file","name":"modifiers_storage.png"},
        {"type":"file","name":"modifiers_storage.svg"}
      ]},
      {"type":"file","name":"Generic GCP.png"},
      {"type":"file","name":"Generic GCP.svg"},
      {"type":"file","name":"Google Cloud Platform.png"},
      {"type":"file","name":"Google Cloud Platform.svg"},
      {"type":"file","name":"Google Cloud Platform_lockup.png"},
      {"type":"file","name":"Google Cloud Platform_lockup.svg"},
      {"type":"directory","name":"Open Source Icons","contents":[
        {"type":"file","name":"Forseti_lockup.png"},
        {"type":"file","name":"Forseti_lockup.svg"},
        {"type":"file","name":"Forseti_logo.png"},
        {"type":"file","name":"Forseti_logo.svg"},
        {"type":"file","name":"Istio_logo.png"},
        {"type":"file","name":"Istio_logo.svg"},
        {"type":"file","name":"Kubernetes_logo.png"},
        {"type":"file","name":"Kubernetes_logo.svg"},
        {"type":"file","name":"Kubernetes_name.png"},
        {"type":"file","name":"Kubernetes_name.svg"},
        {"type":"file","name":"TensorFlow_lockup.png"},
        {"type":"file","name":"TensorFlow_logo.png"},
        {"type":"file","name":"TensorFlow_logo.svg"}
      ]},
      {"type":"file","name":"Prediction API.png"},
      {"type":"file","name":"Prediction API.svg"}
    ]},
    {"type":"directory","name":"Identity &amp; Security","contents":[
      {"type":"file","name":"BeyondCorp.png"},
      {"type":"file","name":"BeyondCorp.svg"},
      {"type":"file","name":"Cloud IAM.png"},
      {"type":"file","name":"Cloud IAM.svg"},
      {"type":"file","name":"Cloud Resource Manager.png"},
      {"type":"file","name":"Cloud Resource Manager.svg"},
      {"type":"file","name":"Cloud Security Command Center.png"},
      {"type":"file","name":"Cloud Security Command Center.svg"},
      {"type":"file","name":"Cloud Security Scanner.png"},
      {"type":"file","name":"Cloud Security Scanner.svg"},
      {"type":"file","name":"Data Loss Prevention API.png"},
      {"type":"file","name":"Data Loss Prevention API.svg"},
      {"type":"file","name":"Identity-Aware Proxy.png"},
      {"type":"file","name":"Identity-Aware Proxy.svg"},
      {"type":"file","name":"Key Management Service.png"},
      {"type":"file","name":"Key Management Service.svg"},
      {"type":"file","name":"Security Key Enforcement.png"},
      {"type":"file","name":"Security Key Enforcement.svg"}
    ]},
    {"type":"directory","name":"Internet of Things","contents":[
      {"type":"file","name":"Cloud IoT Core.png"},
      {"type":"file","name":"Cloud IoT Core.svg"}
    ]},
    {"type":"directory","name":"Management Tools","contents":[
      {"type":"file","name":"Cloud APIs.png"},
      {"type":"file","name":"Cloud APIs.svg"},
      {"type":"file","name":"Cloud Billing API.png"},
      {"type":"file","name":"Cloud Billing API.svg"},
      {"type":"file","name":"Cloud Console.png"},
      {"type":"file","name":"Cloud Console.svg"},
      {"type":"file","name":"Cloud Deployment Manager.png"},
      {"type":"file","name":"Cloud Deployment Manager.svg"},
      {"type":"file","name":"Cloud Mobile App.png"},
      {"type":"file","name":"Cloud Mobile App.svg"},
      {"type":"file","name":"Cloud Shell.png"},
      {"type":"file","name":"Cloud Shell.svg"},
      {"type":"file","name":"Debugger.png"},
      {"type":"file","name":"Debugger.svg"},
      {"type":"file","name":"Error Reporting.png"},
      {"type":"file","name":"Error Reporting.svg"},
      {"type":"file","name":"Logging.png"},
      {"type":"file","name":"Logging.svg"},
      {"type":"file","name":"Monitoring.png"},
      {"type":"file","name":"Monitoring.svg"},
      {"type":"file","name":"Stackdriver.png"},
      {"type":"file","name":"Stackdriver.svg"},
      {"type":"file","name":"Trace.png"},
      {"type":"file","name":"Trace.svg"}
    ]},
    {"type":"directory","name":"Networking","contents":[
      {"type":"file","name":"Cloud Armor.png"},
      {"type":"file","name":"Cloud Armor.svg"},
      {"type":"file","name":"Cloud CDN.png"},
      {"type":"file","name":"Cloud CDN.svg"},
      {"type":"file","name":"Cloud DNS.png"},
      {"type":"file","name":"Cloud DNS.svg"},
      {"type":"file","name":"Cloud External IP Addresses.png"},
      {"type":"file","name":"Cloud External IP Addresses.svg"},
      {"type":"file","name":"Cloud Firewall Rules.png"},
      {"type":"file","name":"Cloud Firewall Rules.svg"},
      {"type":"file","name":"Cloud Load Balancing.png"},
      {"type":"file","name":"Cloud Load Balancing.svg"},
      {"type":"file","name":"Cloud Network.png"},
      {"type":"file","name":"Cloud Network.svg"},
      {"type":"file","name":"Cloud Router.png"},
      {"type":"file","name":"Cloud Router.svg"},
      {"type":"file","name":"Cloud Routes.png"},
      {"type":"file","name":"Cloud Routes.svg"},
      {"type":"file","name":"Cloud VPN.png"},
      {"type":"file","name":"Cloud VPN.svg"},
      {"type":"file","name":"Dedicated Interconnect.png"},
      {"type":"file","name":"Dedicated Interconnect.svg"},
      {"type":"file","name":"Partner Interconnect.png"},
      {"type":"file","name":"Partner Interconnect.svg"},
      {"type":"file","name":"Premium Network Tier.png"},
      {"type":"file","name":"Premium Network Tier.svg"},
      {"type":"file","name":"Standard Network Tier.png"},
      {"type":"file","name":"Standard Network Tier.svg"},
      {"type":"file","name":"Virtual Private Cloud.png"},
      {"type":"file","name":"Virtual Private Cloud.svg"}
    ]},
    {"type":"directory","name":"Storage &amp; Databases","contents":[
      {"type":"file","name":"Cloud Bigtable.png"},
      {"type":"file","name":"Cloud Bigtable.svg"},
      {"type":"file","name":"Cloud Datastore.png"},
      {"type":"file","name":"Cloud Datastore.svg"},
      {"type":"file","name":"Cloud Filestore.png"},
      {"type":"file","name":"Cloud Filestore.svg"},
      {"type":"file","name":"Cloud Memorystore.png"},
      {"type":"file","name":"Cloud Memorystore.svg"},
      {"type":"file","name":"Cloud SQL.png"},
      {"type":"file","name":"Cloud SQL.svg"},
      {"type":"file","name":"Cloud Spanner.png"},
      {"type":"file","name":"Cloud Spanner.svg"},
      {"type":"file","name":"Cloud Storage.png"},
      {"type":"file","name":"Cloud Storage.svg"},
      {"type":"file","name":"Persistent Disk.png"},
      {"type":"file","name":"Persistent Disk.svg"}
    ]}
  ]},
  {"type":"report","directories":14,"files":231}
]

export default Icons;
